main: me.magicmceu.GodWarsPlugin
name: GodWarsPlugin
version: 0.0.1
authors: [ItsWers0n, Tomczyq_]

commands:
  vortex:
    permission: godwars.give.vortex
    permission-message: "§4You don't have permission to use this command"
    description: Gives you Vortex!
  inferno:
    permission: godwars.give.inferno
    permission-message: "§4You don't have permission to use this command"
    description: Gives you Inferno!